.TH crimesquad 6 2007-06-16
.SH NAME
crimesquad - リベラル・クライム・スコード
.SH DESCRIPTION
.P
急進的なエリート・リベラルをスカウトし、腐敗した保守強硬派からアメリカ合衆国
を救うために戦う風刺的なコンソールベースの政治ロール・プレイング/戦略ゲームで
す。このゲームは1983年のRPG Oublietteを元にしています。
.P
プレーのための情報はマニュアルを読んでください。マニュアルはダウンロードした
アーカイブのフォルダにありますが、オンラインでも読めます。
.SH AVAILABILITY
全てのUNIXとwin32
.SH REQUIRES
ncurses (win32ならばpdcurses)
.SH AUTHORS
Tarn Adams - このゲームの原作者
.br
Kevin Sadler - Linuxへの移植とバグ修正
.P
現在の開発者: 
.P
Jonathan Stickles (jonathansfox@users.sourceforge.net)
.br
Chris Johnson (grundee@users.sourceforge.net)

